TESTS = embed_all_bits.sh \
        embed_extract_ecc.sh \
        embed_extract_jpg.sh \
        embed_extract_pnm.sh \
        embed_extract_ppm.sh \
        test_seek.sh

CLEANFILES =  noise-with-message.jpg \
              noise-with-ecc.jpg \
              embed-all-bits.log \
              text-all-bits.txt \
              text-ecc.txt \
              test-with-message.jpg \
              test-with-message.pnm \
              test-with-message.ppm

distclean-local:
	rm -f out.jpg
